---
- name: variables
  hosts: web
  vars:  # play level variables. All tasks under this play have access to these variables
    COURSE: "devops with aws"
    DURATION: 120Hrs
    TRAINER: Usha
  tasks:
  - name: print the information using variables
    ansible.builtin.debug:
      msg: "Learning {{COURSE}} with duration {{DURATION}} and Trainer is {{TRAINER}}"

  - name: print the information again
    vars:   #task level variables. Overwrites play level variables. If the same vaibale name used in tasks, then task level variable has preference
      COURSE:  Ansible
    ansible.builtin.debug:
      msg: "Learning {{COURSE}} with duration {{DURATION}} and Trainer is {{TRAINER}}"

  - name: print the information again and again
    ansible.builtin.debug:
      msg: "Learning {{COURSE}} with duration {{DURATION}} and Trainer is {{TRAINER}}"
