---
- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER  # store the output of above command to USER
    ignore_errors: Ture

  - name: print the user information
    anisble.builtin.debug:
      msg: "user info:  {{USER}}"

  - name: cretae user, if does not exist
    ansible.builtin.commad: useradd expense
    when: USER.rc != 0  # rc is return code
    
