---
- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: print the OS stats
    ansible.builtin.debug: 
      msg: "facts are: {{ansible_facts}}"

  - name: install nginx if RedHat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx if Ubuntu/Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
